### ISSUE TITLE
Idea: DNS-integrated dynamic configuration

### ISSUE THREAD

**Issue by Ashald** [linkerd/linkerd-tcp#34]
Just an idea to consider, but if it was supported by Linkerd-tcp it would've been so amazing and would've switched to it immediately.

Imagine a host that has:
* linkerd-tcp
* some kind of lightweight DNS-server (like dnsmasq)
* an application

Let's say the application needs to talk to MS SQL Server and we want to do that through linkerd-tcp. Instead of pre-configuring linkerd-tcp with an endpoint for that specific DB endpoint (if we want to use 1 instance for many apps or app talks to a lot of services/endpoints) the app can attempt to connect to something like `__1433__.foobar-database.linkerd` where `.linkerd` is just a TLD that we decided to use in this case. Our host will be configured to use `dnsmasq` running locally to resolve DNS names and the `dnsmasq` will be configured to forward requests for `.linkerd` to `linkerd-tcp` DNS interface running on some port on the localhost. When linkerd-tcp will get a DNS request for `__1433__.foobar-database.linkerd` it can setup a listener on port `1433` on some unique loopback IPv4 (there are millions of them since there is a huge subnet for loopback addresses like 127/24) like `127.213.233.132` and send that IPv4 as an `A` record with DNS reply.
Now the application will connect to the `127.213.233.132:1433` thinking it's an MS SQL Server instance and linkerd-tcp will be already listening there prepared to proxy traffic.

This is just an abstract idea and probably the "DNS schema" can designed more properly to allow "dtab overrides" and/or "per client routing".

My main goal here is to learn whether it's something you planing to do with linkerd-tcp or you have an alternative solution or it's something out of scope in your plans?

**Comment by olix0r** [comment]
I don't think we want to add a DNS server into the proxy itself, at least not in the nearterm future. We're more likely to focus on providing a richer configuration API for the proxy, so that this sort of thing can be implemented at a higher level.  But I don't think we'd want to have any tight coupling like this in this project.

**Comment by Ashald** [comment]
That makes sense, thanks for an explanation! Looking forward for the configuration API you mentioned. ;)
