### ISSUE TITLE
Update rustls and mio versions

### ISSUE THREAD

**Issue by moderation** [linkerd/linkerd-tcp#58]
Rustls has moved to version 0.8 (https://github.com/ctz/rustls/commit/339bd8513317f5c692d77c5c3ad068b207dd82e5) and updated its mio dependency to 0.6 (https://github.com/ctz/rustls/commit/14e9529e406065efe23f4de9112601d896820716).

**Comment by stevej** [comment]
Thanks! I have an upgrade for that sitting in #55 and will pester oliver for a review again.

**Comment by moderation** [comment]
In my testing I've upgraded the serde* crates (in addition to rustls) to their 1.0.* versions and have compiled successfully. Diff is:

```
clap = "2.24"
rustls = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
```
I was going to put a PR in but will wake until https://github.com/linkerd/linkerd-tcp/pull/55 lands.

**Comment by stevej** [comment]
#55 has landed. You're welcome to send a PR or I can pick up it later. Thanks, regardless!

**Comment by moderation** [comment]
Closed by https://github.com/linkerd/linkerd-tcp/pull/59.
