### ISSUE TITLE
Binary building fails due to incorrect commit-id for rustls in cargo.lock

### ISSUE THREAD

**Issue by scanterog** [linkerd/linkerd-tcp#79]
Hi guys,

Commit-id for https://github.com/linkerd/linkerd-tcp/blob/master/Cargo.lock#L524 does not exist. What I've done is to replace it with last commit (ba6c42c) for same branch (make_server_sni_public) and compilation finished successfully. I can confirm binary is working fine for me.

**Comment by xusss** [comment]
Change the commit-id of `rustls` in `Cargo.lock` just work.
I think maybe some one rebase commit history cause this error happend.

**Comment by wmorgan** [comment]
Thanks @xusss!

**Comment by briansmith** [comment]
> Commit-id for https://github.com/linkerd/linkerd-tcp/blob/master/Cargo.lock#L524 does not exist. What I've done is to replace it with last commit (ba6c42c) for same branch (make_server_sni_public) and compilation finished successfully.

Thanks! I am used to working on projects that don't check Cargo.lock into version control so I didn't realize that this would even be an issue. In the short term, #81 should resolve this. Later, we'll make it so there's no more `git` dependencies again too.
